name: Deploy Lambda Function to AWS

on:
  push:
    branches:
      - dev   # Run workflow on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python environment (adjust the version if needed)
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Step 3: Install dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r lambda/requirements.txt

      # Step 2: Set up AWS CLI
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

      # Step 4: Package Lambda code
      - name: Zip Lambda code
        run: |
          cd lambda
          zip -r ../lambda-code.zip .   # Zips the contents of the lambda folder

      # Step 5: Upload the Lambda package to S3
      - name: Upload Lambda code to S3
        run: aws s3 cp lambda-code.zip s3://vmistry-f1-dashboard/lambda-code.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'

      - name: Check if CloudFormation stack exists
        id: stack_check
        run: |
          STACK_NAME="F1RaceInsightsStack"
          if aws cloudformation describe-stacks --stack-name $STACK_NAME; then
            echo "Stack $STACK_NAME exists."
            echo "::set-output name=stack_exists::true"
          else
            echo "Stack $STACK_NAME does not exist."
            echo "::set-output name=stack_exists::false"
          fi

      - name: Deploy or Update CloudFormation stack
        run: |
          STACK_NAME="F1RaceInsightsStack"
          if [[ "${{ steps.stack_check.outputs.stack_exists }}" == "true" ]]; then
            echo "Updating stack $STACK_NAME."
            aws cloudformation update-stack \
              --stack-name $STACK_NAME \
              --template-file infrastructure/cloudformation.yml \
              --capabilities CAPABILITY_NAMED_IAM
          else
            echo "Creating stack $STACK_NAME."
            aws cloudformation create-stack \
              --stack-name $STACK_NAME \
              --template-file infrastructure/cloudformation.yml \
              --capabilities CAPABILITY_NAMED_IAM
          fi

     


