name: Deploy Lambda Function to AWS

on:
  push:
    branches:
      - main   # Run workflow on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python environment (adjust the version if needed)
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Step 3: Install dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r lambda/requirements.txt

      # Step 4: Package Lambda code
      - name: Zip Lambda code
        run: |
          cd lambda
          zip -r ../lambda-code.zip .   # Zips the contents of the lambda folder

      # Step 5: Upload the Lambda package to S3
      - name: Upload Lambda code to S3
        run: aws s3 cp lambda-code.zip s3://vmistry-f1-dashboard/lambda-code.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'

      # Step 4: Deploy CloudFormation stack
      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file infrastructure/cloudformation.yml \
            --stack-name F1RaceInsightsStack \
            --capabilities CAPABILITY_NAMED_IAM


